export const homeImages = [
  "1 better.webp",
  "2 better.webp",
  "alex 21.webp",
  "alex 22.webp",
  "another tuff shoot.webp",
  "bbbbluekenndedy.webp",
  "bbbbluekennndey.webp",
  "bbblue ken.webp",
  "bluebluekenndey.webp",
  "bluebluekenny.webp",
  "cap 1.webp",
  "cap 2.webp",
  "cap 3.webp",
  "cap 4.webp",
  "cap 5.webp",
  "eunice 100.webp",
  "eunice 103.webp",
  "eunice 132.webp",
  "eunice 140.webp",
  "eunice 141.webp",
  "eunice 183.webp",
  "eunice 185.webp",
  "eunice 186.webp",
  "eunice 187.webp",
  "eunice 197.webp",
  "eunice 203.webp",
  "eunice 211.webp",
  "eunice 80.webp",
  "eunice 94.webp",
  "faith 1.webp",
  "faith 11.webp",
  "faith 3.webp",
  "faith 6.webp",
  "faith 9.webp",
  "ff1.webp",
  "ff2.webp",
  "fire.webp",
  "flowers flowers mone.webp",
  "fujah fashion 4.webp",
  "fujah fashion 677.webp",
  "golden 3.webp",
  "golden 6.webp",
  "golden 7.webp",
  "golden 8.webp",
  "golden 9.webp",
  "groom 1.webp",
  "groom 15.webp",
  "groom 16.webp",
  "groom 18.webp",
  "groom 25.webp",
  "groom 26.webp",
  "mb21.webp",
  "mb22.webp",
  "mb23.webp",
  "mb27.webp",
  "mb3.webp",
  "mb4.webp",
  "mone tem 1.webp",
  "mone tem 5.webp",
  "mone tem 6.webp",
  "n1.webp",
  "n10.webp",
  "n2.webp",
  "n20.webp",
  "n3.webp",
  "n4.webp",
  "n7.webp",
  "perfect blue.webp",
  "punkun 1.webp",
  "punkun 7.webp",
  "ryah 2.webp",
  "ryah 4.webp",
  "tay 1.webp",
  "tay 5.webp",
  "this is the best one.webp",
  "toughhhhhhnh.webp",
  "touigh karlllwew.webp",
  "trying out.webp",
  "with png smotth.webp",
  "with shadow.webp",
  "withththth gtain.webp",
  "x8x.webp"
];

export const weddingsImages = [
  "1 better.webp",
  "2 better.webp",
  "eunice 100.webp",
  "eunice 103.webp",
  "eunice 132.webp",
  "eunice 140.webp",
  "eunice 141.webp",
  "eunice 183.webp",
  "eunice 185.webp",
  "eunice 186.webp",
  "eunice 187.webp",
  "eunice 197.webp",
  "eunice 203.webp",
  "eunice 211.webp",
  "eunice 224.webp",
  "eunice 240.webp",
  "eunice 246.webp",
  "eunice 249.webp",
  "eunice 259.webp",
  "eunice 260.webp",
  "eunice 261.webp",
  "eunice 262.webp",
  "eunice 289.webp",
  "eunice 299.webp",
  "eunice 300.webp",
  "eunice 80.webp",
  "eunice 94.webp",
  "eunice eight.webp",
  "eunice five.webp",
  "eunice four.webp",
  "eunice nine.webp",
  "eunice onr.webp",
  "eunice seven.webp",
  "eunice six.webp",
  "eunice ten.webp",
  "eunice three.webp",
  "eunice two.webp",
  "groom 1.webp",
  "groom 15.webp",
  "groom 16.webp",
  "groom 18.webp",
  "groom 25.webp",
  "groom 26.webp",
  "mb21.webp",
  "mb22.webp",
  "mb23.webp",
  "mb27.webp",
  "mb3.webp",
  "mb4.webp",
  "n1.webp",
  "n10.webp",
  "n2.webp",
  "n20.webp",
  "n3.webp",
  "n4.webp",
  "n7.webp"
];

export const portraitsImages = [
  "111 karL.webp",
  "1222222224444444444444 tough.webp",
  "222 karL.webp",
  "33333 karl - Copy.webp",
  "784267823.webp",
  "GOLD ORANGE.webp",
  "KEEEN.webp",
  "alex 13.webp",
  "alex 14.webp",
  "alex 17.webp",
  "alex 18.webp",
  "alex 20.webp",
  "alex 21.webp",
  "alex 22.webp",
  "another tuff shoot.webp",
  "bbbbluekenndedy.webp",
  "bbbbluekennndey.webp",
  "bbblue ken.webp",
  "bluebluekenndey.webp",
  "bluebluekenny.webp",
  "cap 1.webp",
  "cap 2.webp",
  "cap 3.webp",
  "cap 4.webp",
  "cap 5.webp",
  "crouching mone.webp",
  "danicng orange.webp",
  "dddd fire.webp",
  "editorial-sammmy!_01.webp",
  "editorial-sammmy!_02.webp",
  "editorial-sammmy!_03.webp",
  "editorial-sammmy!_07.webp",
  "face shot mone.webp",
  "face tuned portaits.webp",
  "faith 1.webp",
  "faith 11.webp",
  "faith 3.webp",
  "faith 6.webp",
  "faith 9.webp",
  "ff1.webp",
  "ff2.webp",
  "fire.webp",
  "flowers flowers mone.webp",
  "fujah fashion 4.webp",
  "fujah fashion 677.webp",
  "fuji fuji orange.webp",
  "fuji houston.webp",
  "golden 1.webp",
  "golden 10.webp",
  "golden 3.webp",
  "golden 6.webp",
  "golden 7.webp",
  "golden 8.webp",
  "golden 9.webp",
  "happy alexis.webp",
  "houston honey.webp",
  "i think better orange.webp",
  "karliea.webp",
  "keeeenneyblue.webp",
  "kennedy blue.webp",
  "moine feel.webp",
  "mone landscape.webp",
  "mone tem 1.webp",
  "mone tem 11.webp",
  "mone tem 2.webp",
  "mone tem 3.webp",
  "mone tem 5.webp",
  "mone tem 6.webp",
  "mone tem 8.webp",
  "mone vevo.webp",
  "perfect blue.webp",
  "photo xii.webp",
  "photo xviii.webp",
  "photo xvixx.webp",
  "porrtrait moe.webp",
  "punkun 1.webp",
  "punkun 10.webp",
  "punkun 3.webp",
  "punkun 7.webp",
  "punkun.webp",
  "ryah 11.webp",
  "ryah 2.webp",
  "ryah 3.webp",
  "ryah 4.webp",
  "ryah 7.webp",
  "sideways mone.webp",
  "stare orange.webp",
  "stare smile.webp",
  "tay 1.webp",
  "tay 2.webp",
  "tay 4.webp",
  "tay 5.webp",
  "this is the best one.webp",
  "toughhhhhhnh.webp",
  "touigh karlllwew.webp",
  "trying out.webp",
  "with png smotth.webp",
  "with shadow.webp",
  "withththth gtain.webp",
  "x8x.webp"
];

