export const homeImages = [
  "1 better.png",
  "111 karL.png",
  "1222222224444444444444 tough.png",
  "2 better.png",
  "another tuff shoot.png",
  "bride 29.png",
  "bride 31.png",
  "bride 32.png",
  "bride 34.png",
  "bride 45.png",
  "danicng orange.png",
  "dddd fire.png",
  "eunice 100.png",
  "eunice 173.png",
  "eunice 178.png",
  "eunice 183.png",
  "eunice 185.png",
  "eunice 187.png",
  "eunice 190.png",
  "eunice 197.png",
  "eunice 213.png",
  "eunice 221.png",
  "eunice 222.png",
  "eunice 224.png",
  "eunice 225.png",
  "eunice 242.png",
  "eunice 245.png",
  "eunice 39.png",
  "eunice 68.png",
  "eunice 70.png",
  "eunice 71.png",
  "eunice 77.png",
  "eunice 85.png",
  "eunice 86.png",
  "face tuned portaits.png",
  "faith 1.png",
  "faith 11.png",
  "faith 3.png",
  "faith 6.png",
  "faith 9.png",
  "ff1.png",
  "ff2.png",
  "stare smile.png",
  "tay 5.png",
  "toughhhhhhnh.png"
];

export const weddingsImages = [
  "1 better.png",
  "2 better.png",
  "bride 29.png",
  "bride 31.png",
  "bride 32.png",
  "bride 34.png",
  "bride 45.png",
  "eunice 100.png",
  "eunice 166.png",
  "eunice 173.png",
  "eunice 178.png",
  "eunice 183.png",
  "eunice 185.png",
  "eunice 187.png",
  "eunice 190.png",
  "eunice 197.png",
  "eunice 213.png",
  "eunice 221.png",
  "eunice 222.png",
  "eunice 224.png",
  "eunice 225.png",
  "eunice 242.png",
  "eunice 245.png",
  "eunice 248.png",
  "eunice 289.png",
  "eunice 299.png",
  "eunice 39.png",
  "eunice 68.png",
  "eunice 70.png",
  "eunice 71.png",
  "eunice 77.png",
  "eunice 85.png",
  "eunice 86.png",
  "eunice six.png",
  "eunice three.png",
  "eunice two.png",
  "groom 1.png",
  "groom 1444.png",
  "groom 15.png",
  "groom 16.png",
  "groom 18.png",
  "groom 25.png",
  "groom 26.png",
  "mb11.png",
  "mb19.png",
  "mb20.png",
  "mb21.png",
  "mb22.png",
  "mb23.png",
  "mb27.png",
  "mb4.png",
  "n1.png",
  "n10.png",
  "n14.png",
  "n2.png",
  "n20.png",
  "n3.png",
  "n4.png",
  "n7.png"
];

export const portraitsImages = [
  "111 karL.png",
  "1222222224444444444444 tough.png",
  "222 karL.png",
  "33333 karl - Copy.png",
  "GOLD ORANGE.png",
  "another tuff shoot.png",
  "danicng orange.png",
  "dddd fire.png",
  "editorial-sammmy!_01.png",
  "editorial-sammmy!_02.png",
  "editorial-sammmy!_03.png",
  "editorial-sammmy!_07.png",
  "face tuned portaits.png",
  "faith 1.png",
  "faith 11.png",
  "faith 3.png",
  "faith 6.png",
  "faith 9.png",
  "ff1.png",
  "ff2.png",
  "fire.png",
  "fujah fashion 4.png",
  "fujah fashion 677.png",
  "fuji fuji orange.png",
  "happy alexis.png",
  "i think better orange.png",
  "karliea.png",
  "moine feel.png",
  "mone tem 1.png",
  "mone tem 11.png",
  "mone tem 2.png",
  "mone tem 3.png",
  "mone tem 5.png",
  "mone tem 6.png",
  "mone tem 8.png",
  "photo xii.png",
  "photo xviii.png",
  "photo xvixx.png",
  "punkun 1.png",
  "punkun 10.png",
  "punkun 3.png",
  "punkun 7.png",
  "punkun.png",
  "stare orange.png",
  "stare smile.png",
  "tay 1.png",
  "tay 2.png",
  "tay 4.png",
  "tay 5.png",
  "toughhhhhhnh.png",
  "touigh karlllwew.png",
  "with png smotth.png",
  "withththth gtain.png",
  "x8x.png"
];

